### ISSUE TITLE
Empty queue issue

### ISSUE THREAD

**Issue by trz-maier** [trz-maier/hwu-ase-group3#133]
Sometimes when program opens Server tries to take an Order from an empty queue - before the first item appears. This causes the error shown below.

![image](https://user-images.githubusercontent.com/46493724/54075720-74979a00-429a-11e9-9048-a16b5991fbde.png)

**Comment by Orangefruit2** [comment]
Dont be confused by the Logging message.
If I go to a shop and there is no queue. The Server can directly handle my order. Thereforce, the Server took my Order, and 0 people are in the queue.

**Comment by trz-maier** [comment]
This however caused the server not starting correctly for some reason, i.e. server 1 would just not handle any orders until the program closes. Not sure if you can replicate this issue but it happened to me twice

**Comment by Orangefruit2** [comment]
what do you mean?

**Comment by trz-maier** [comment]
It happened to me twice that after this error appeared the 1st server would never accept any other orders until all orders were done

**Comment by Orangefruit2** [comment]
Even with the pull request bugfix?
