### ISSUE TITLE
Create OrderController Class

### ISSUE THREAD

**Issue by trz-maier** [trz-maier/hwu-ase-group3#15]
Add OrderController Class with basic functionality

**Comment by jathanasiou** [comment]
Implementation should be

- [ ] Initialized with main process
- [ ] Initializing the GUI frame
- [ ] Populating the program item/order data via FileReader
- [ ] Managing model instances
- [ ] Have implemented methods to be called by GUI

**Comment by jathanasiou** [comment]
Pending testing on initializing+reading. Build is not possible yet.
