### ISSUE TITLE
NullPointerException on program start

### ISSUE THREAD

**Issue by trz-maier** [trz-maier/hwu-ase-group3#156]
Difficult to replicate as this happens at random but there seems to be an issue when starting up the program and updating queue frame in the wrong order. Perhaps some added delay in processing would solve the problem? It could happen during presentation which would be very unlucky but would require us closing the program and starting over.

![image](https://user-images.githubusercontent.com/46493724/54498227-6bdb3f80-48fc-11e9-9995-3d2ae1d85af5.png)

**Comment by jathanasiou** [comment]
Is there a chance your app already had threads running (Red square "stop" button of the IDE enabled)? I think it happened to me once or twice as well, but I seem to recall it was because the app wasn't terminated properly before.

**Comment by trz-maier** [comment]
umm I do not think so. This seems to be related to #133, just a different error thrown. Based on the log the program calls update frame before any order is produced, even before any Server starts

![image](https://user-images.githubusercontent.com/46493724/54513515-92769600-494f-11e9-8d1d-623edc9d342c.png)


![image](https://user-images.githubusercontent.com/46493724/54513407-44fa2900-494f-11e9-9997-cb33166c3a3f.png)
