### ISSUE TITLE
Add getStockItems method in OrderController

### ISSUE THREAD

**Issue by trz-maier** [trz-maier/hwu-ase-group3#32]

**Comment by jathanasiou** [comment]
As per class diagram, it is the `OrderFrame` class which should have a passive `setStockItems(...)` method, to be called by the controller. Therefore, no such method needs to be added to the OrderController itself.
![screenshot from 2019-02-11 17-03-04](https://user-images.githubusercontent.com/8679925/52579877-0dafce00-2e1f-11e9-84e2-7588d5d265b0.png)

Closing this as 'wontfix'.
