### ISSUE TITLE
Re-format items.txt so it can be read by FileReader

### ISSUE THREAD

**Issue by trz-maier** [trz-maier/hwu-ase-group3#36]

**Comment by jathanasiou** [comment]
It appears that in spite of the merge there is an issue with the UUID values in the master branch.

`Exception in thread "main" java.lang.IllegalArgumentException: The UUID=FOOD001 is not correctly formatted`

@Orangefruit2 is this an error on parsing logic or do we need to fix the items.txt file?

**Comment by Orangefruit2** [comment]
It is not correctly formatted(UUID string looks like this: cdd15ee5-a560-4aa2-be61-fe5ec82ab3b0).
There should be some examples in Orders.txt.
You can generate a UUID string by calling UUID.randomUUID().toString();

**Comment by jathanasiou** [comment]
There is no `orders.txt` in the master branch. Should it be there?  

Also, since we agreed on having the name+uuid value as key shouldn't [this line](https://github.com/trz-maier/hwu-ase-group3/blob/master/src/ase/cw/IO/FileReader.java#L116)

be 
```java
items.put(item.getName() + item.getId(), item); //items := treemap
```

instead?

**Comment by jathanasiou** [comment]
It appears that proper input files are placed under the `/res/` directory and I was a reading a test/sample file instead. Will be fixing it myself.
