### ISSUE TITLE
override toString() methods for Item and OrderItem

### ISSUE THREAD

**Issue by trz-maier** [trz-maier/hwu-ase-group3#48]
as requested, as this is apparently unclear - this is required to display the items correctly

![image](https://user-images.githubusercontent.com/46493724/52978622-fb5b0480-33c9-11e9-9287-6a4d8f581077.png)

**Comment by jathanasiou** [comment]
Please add description/need and close if resolved in PR #53

**Comment by trz-maier** [comment]
@jathanasiou this was fixed indeed but overridden by another merge...

**Comment by trz-maier** [comment]
It would be appropriate for the string to contain price, i.e. 
`Cheese Sandwich (£1.99)`
