### ISSUE TITLE
Exception for trying to remove/add Item without selection, i.e. InvalidItemException

### ISSUE THREAD

**Issue by trz-maier** [trz-maier/hwu-ase-group3#51]
could we consider adding an exception to handle calling add/remove item buttons without passing any items/orderitems as parameters?

**Comment by jathanasiou** [comment]
We can simply use [IllegalStateException](https://docs.oracle.com/javase/7/docs/api/java/lang/IllegalStateException.html).

**Comment by trz-maier** [comment]
John would this be defined in OrderController? at the moment nothing happens for Frame to catch

**Comment by jathanasiou** [comment]
Should be working as intended as per #54

**Comment by trz-maier** [comment]
this is not what I meant John. seems like an empty call to removeItemFromPendingOrder() does not have any effect while an empty call to addItemToPendingOrder() throws a NullPointerException. what you added isn't required if these two are implemented

**Comment by jathanasiou** [comment]
After discussion, the PR has been updated to included the actually needed exceptions. Apologies for misunderstanding.
