### ISSUE TITLE
OrderController to print actions into the console

### ISSUE THREAD

**Issue by trz-maier** [trz-maier/hwu-ase-group3#52]
not sure if this is something always done or if anyone thinks there is any use in it but I like to see an entry in the console each time a function is called successfully, i.e. printing 

ORDER: Item X added to order. Cart items: 5
ORDER: Order has been submitted.

or something along those lines?  

I had this earlier in the OrderFrame but from there I can't  be certain that these actions took place, only that the functions were called.

**Comment by jathanasiou** [comment]
Closing in favor of #100
