### ISSUE TITLE
Add final report method

### ISSUE THREAD

**Issue by trz-maier** [trz-maier/hwu-ase-group3#63]
Final report to be added in `OrderController` class (I assume). Please reassign if you have a different opinion. I will add a setter taking a String as a parameter, i.e. `setFinalReport()` in the `OrderFrame` to follow the similar setters already in place.

**Comment by jathanasiou** [comment]
I think we could just make the controller's `generateReport()` return a String since the frame will be doing the request.

**Comment by trz-maier** [comment]
@jathanasiou apologies I missed this thread. either way will be fine, you are probably right that the Controller should be able to write a report into a file without Frame intervention so what you are proposing is reasonable

**Comment by jathanasiou** [comment]
Missing a line break in the output, will be fixing with a further commit.
