### ISSUE TITLE
Add some form of validation of customer id

### ISSUE THREAD

**Issue by trz-maier** [trz-maier/hwu-ase-group3#64]
at the moment I can pass `????????` as customer id so I think it would be worth adding some form of validation and throw another `InvalidCustomerIdException` - either just numbers or perhaps alphanumeric characters only?

![image](https://user-images.githubusercontent.com/46493724/53055283-0895f300-349f-11e9-8198-0f950d084b32.png)

**Comment by jathanasiou** [comment]
> alphanumeric characters only?

I will implement this + fixed length. Hope that sounds ok. Once that is done we will have to align our `orders.txt`

**Comment by jathanasiou** [comment]
@trz-maier please check if it works on your side and close if everything's good :)
