### ISSUE TITLE
Price not displayed correctly in frame

### ISSUE THREAD

**Issue by trz-maier** [trz-maier/hwu-ase-group3#71]
![image](https://user-images.githubusercontent.com/46493724/53121204-90d1d200-354b-11e9-90d4-5404d7514d2f.png)

**Comment by jathanasiou** [comment]
Perhaps this is related to #50  ? Was that fixed at the time?   

Some marginal values like `0.01` or `0.99` are prone to causing such outputs. 

@trz-maier  if you have a replication scenario *(add X, then add Y...)* I would recommend writing it down here so that we can look into it.

**Comment by trz-maier** [comment]
I think I fixed it, thanks anyway @jathanasiou
