### ISSUE TITLE
Create submission report

### ISSUE THREAD

**Issue by trz-maier** [trz-maier/hwu-ase-group3#78]

**Comment by jathanasiou** [comment]
Document link provided by @Orangefruit2 [here](https://1drv.ms/w/s!ArXCCjwLCa2Zge41tvxgm_gMadLTRg).

**Comment by trz-maier** [comment]
was this document shared via University account or just shared as a link? I don't seem to be able to get into it from my University login

**Comment by jathanasiou** [comment]
@trz-maier we need non-university MS accounts to view this particular one.
